function [BW,maskedImage] = segmentImage_europeo6_frame10(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Dec-2024
%----------------------------------------------------


% Adjust data to span data range.
RGB = imadjust(RGB);


% Create empty mask
BW = false(size(RGB,1),size(RGB,2));

% Segment Anything Model
% Load Segment Anything Model
sam = segmentAnythingModel();

% SAM expects image data to be in the range [0-255].
samImage = 255*rescale(RGB);

% Extract Embeddings for the image to be segmented
embeds = extractEmbeddings(sam, samImage);
imsz = size(samImage, [1 2]);



% Initialize Variables that will track each step of the segmentation
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];

% Remove All markers, ROIs and reset Mask Logits
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];
BW = BW | false(imsz);

fgPoints(end+1, :) = [136 368];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [137 433];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [453 427];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [419 365];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [200 416];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [428 405];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [205 431];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [571 404];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [97 417];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [103 397];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [157 446];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [588 420];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [585 422];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [585 423];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [302 417];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [303 422];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [302 417];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [302 421];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [304 418];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [304 422];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [301 420];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 418];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [302 417];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [302 414];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1:end+0, :) = [];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [302 426];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 420];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [299 416];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [299 421];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [299 423];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 424];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [298 415];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [297 417];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [295 422];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [295 423];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [296 419];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [296 421];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397
    302 421
    304 422
    301 420
    302 426
    300 420
    299 421
    299 423
    300 424
    295 422
    295 423
    296 421];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397
    302 426];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [136 368
    137 433
    453 427
    419 365
    205 431
    571 404
    97 417
    103 397];
bgPoints = [200 416
    428 405
    157 446
    115 445];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [302 419];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [301 422];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [303 422];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [303 420];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

BW = BW | BWout;


% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

