function [BW,maskedImage] = segmentImage_eu6_fr10(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Dec-2024
%----------------------------------------------------


% Adjust data to span data range.
RGB = imadjust(RGB, [0 1], [0 1]);


% Create empty mask
BW = false(size(RGB,1),size(RGB,2));

% Segment Anything Model
% Load Segment Anything Model
sam = segmentAnythingModel();

% SAM expects image data to be in the range [0-255].
samImage = 255*rescale(RGB);

% Extract Embeddings for the image to be segmented
embeds = extractEmbeddings(sam, samImage);
imsz = size(samImage, [1 2]);



% Initialize Variables that will track each step of the segmentation
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];

% Remove All markers, ROIs and reset Mask Logits
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];
BW = BW | false(imsz);

fgPoints(end+1, :) = [221 368];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [575 363];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [122 435];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [485 426];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [577 403];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [99 407];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [157 413];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [254 411];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [420 398];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [398 427];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [572 428];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [444 438];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [101 395];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [94 427];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 419];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [303 418];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 425];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

BW = BW | BWout;


% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

