function [BW,maskedImage] = segmentImage_DL_FULL(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Dec-2024
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Create empty mask
BW = false(size(X,1),size(X,2));

% Segment Anything Model
% Load Segment Anything Model
sam = segmentAnythingModel();

% SAM expects image data to be in the range [0-255].
samImage = 255*rescale(X);

% Extract Embeddings for the image to be segmented
embeds = extractEmbeddings(sam, samImage);
imsz = size(samImage, [1 2]);



% Initialize Variables that will track each step of the segmentation
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];

% Remove All markers, ROIs and reset Mask Logits
fgPoints = [];
bgPoints = [];
bbox = [31.20009 215.0329 601.8323 223.1142];
maskLogits = [];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);


fgPoints(end+1, :) = [176 370];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

BW = BW | BWout;


% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

