function [BW,maskedImage] = segmentImage_GPU_v1(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 10-Dec-2024
%----------------------------------------------------



% Create empty mask
BW = false(size(RGB,1),size(RGB,2));

% Segment Anything Model
% Load Segment Anything Model
sam = segmentAnythingModel();

if canUseGPU()
    RGB = gpuArray(RGB);
end
% SAM expects image data to be in the range [0-255].
samImage = 255*rescale(RGB);

% Extract Embeddings for the image to be segmented
embeds = extractEmbeddings(sam, samImage);
imsz = size(samImage, [1 2]);



% Initialize Variables that will track each step of the segmentation
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];

% Remove All markers, ROIs and reset Mask Logits
fgPoints = [];
bgPoints = [];
bbox = [83.74978 345.1367 534.9006 97.43945];
maskLogits = [];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);


fgPoints(end+1, :) = [199 433];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [580 430];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [195 413];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [98 408];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [100 395];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [108 402];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [119 407];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    98 408
    100 395
    108 402];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    98 408
    100 395];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    98 408];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [98 409];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [100 390];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [101 393];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    98 409];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 423];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [99 407];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [106 399];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    300 423
    99 407];
bgPoints = [195 413
    455 412];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [119 401];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [103 392];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [102 400];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [99 432];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [579 370];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [582 362];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    300 423
    99 407
    103 392
    102 400
    99 432
    582 362];
bgPoints = [195 413
    455 412
    119 401];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    300 423
    99 407
    103 392
    102 400
    99 432];
bgPoints = [195 413
    455 412
    119 401];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [297 426];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [298 417];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    99 407
    103 392
    102 400
    99 432
    297 426];
bgPoints = [195 413
    455 412
    119 401];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    99 407
    103 392
    102 400
    99 432];
bgPoints = [195 413
    455 412
    119 401];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [301 415];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 425];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [300 434];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints = [199 433
    580 430
    99 407
    103 392
    102 400
    99 432
    301 415
    300 425];
bgPoints = [195 413
    455 412
    119 401];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [298 432];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

BW = BW | BWout;


% Close mask with square
width = 30;
se = strel('square', width);
BW = imclose(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

