function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 24-Nov-2024
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Create empty mask
BW = false(size(X,1),size(X,2));

% Segment Anything Model
% Load Segment Anything Model
sam = segmentAnythingModel();

% SAM expects image data to be in the range [0-255].
samImage = 255*rescale(X);

% Extract Embeddings for the image to be segmented
embeds = extractEmbeddings(sam, samImage);
imsz = size(samImage, [1 2]);



% Initialize Variables that will track each step of the segmentation
fgPoints = [];
bgPoints = [];
bbox = [];
maskLogits = [];

fgPoints(end+1, :) = [21 238];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [244 294];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [519 287];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [96 123];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [6 322];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [187 274];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [422 250];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [517 245];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [372 245];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [141 255];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [422 228];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [563 226];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [585 239];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [561 279];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [572 274];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [319 284];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [59 300];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [44 269];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

fgPoints(end+1, :) = [71 243];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

bgPoints(end+1, :) = [177 250];
% Perform Segmentation using the MaskLogits from previous step and all Markers and/or ROIs
[BWout,~,maskLogits] = segmentObjectsFromEmbeddings(sam,embeds,imsz,ForegroundPoints=fgPoints,BackgroundPoints=bgPoints,BoundingBox=bbox,MaskLogits=maskLogits);

BW = BW | BWout;


% Active contour
%iterations = 100;
%BW = activecontour(X, BW, iterations, 'edge');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

