function [BW,maskedImage] = segmentImage(X)
%Tested for "mahel/detect_missing_part/missing_splinter1" frame 25


%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 27-Nov-2024
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Graph cut
foregroundInd = [3478 3494 3603 3873 4072 11964 28112 41280 41408 41505 41536 41663 41664 62227 70263 72231 74487 75394 77905 77906 77923 77930 78010 78153 78168 80468 81586 82002 ];
backgroundInd = [2534 4649 18774 18889 31259 37783 49765 54369 67838 70486 73197 79264 80483 82512 83229 85286 85759 ];
L = superpixels(X,551);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

